services:
  db:
    image: postgres
    expose: 
    - ${DB_PORT}
    ports:
      - 5432:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - sigecap-nt
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PWD=${DB_PWD}
        - APP_PORT=${APP_PORT}
    links:
      - db
    expose:
      - ${APP_PORT}
      - ${DB_PORT}
    ports:
      - 5000:${APP_PORT}
    networks:
      - sigecap-nt
    depends_on:
      - db
networks:
  sigecap-nt:
volumes:
  postgresql:
  postgresql_data: