spring:
  sql:
    init:
      mode: ${APP_DATA_MODE}
  application:
    name: sigecap
  datasource:
    url: jdbc:${APP_DB}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: ${APP_DB_DRIVER}
    data: classpath:data.sql
    initialization-mode: ${APP_DATA_MODE}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: ${APP_JPA_MODE}
    properties:
      hibernate:
        ddl:
          auto: ${APP_JPA_MODE}
    show-sql: ${APP_DEBUG}
  web:
    resources:
      static:
        content-type:
          text/javascript: application/javascript
server:
  port: ${APP_PORT}
logging:
  level:
    root: INFO
    dev.dejack: DEBUG
    #org.hibernate: DEBUG
  file:
    name: data/logs/app.log
    max-size: 10MB
    max-history: 30