spring:
  sql:
    init:
      mode: ${APP_DATA_MODE}
  application:
    name: sigecap
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: classpath:data.sql
    initialization-mode: ${APP_DATA_MODE}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${APP_PORT}