spring:
  sql:
    init:
      mode: ${APP_DATA_MODE}
  application:
    name: sigecap
  datasource:
    url: jdbc:${APP_DB}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: ${APP_DB_DRIVER}
    data: classpath:data.sql
    initialization-mode: ${APP_DATA_MODE}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: ${APP_DEBUG}
  web:
    resources:
      static:
        content-type:
          text/javascript: application/javascript
server:
  port: ${APP_PORT}