apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: kube-system
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1" 
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: DB_PWD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigecap
  namespace: kube-system
  labels:
    app: sigecap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sigecap
  template:
    metadata:
      labels:
        app: sigecap
    spec:
      initContainers:
      - name: init-db-check
        image: busybox
        command:
        - sh
        - -c
        - "until nc -z -v -w30 db 5432; do echo 'Waiting for database...'; sleep 5; done"
      containers:
      - name: sigecap
        image: jacunav/sigecap-docker:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1" 
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: DB_USERNAME
        - name: DB_PWD
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: DB_PWD
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: APP_PORT
        - name: APP_DATA_MODE
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: APP_DATA_MODE
        - name: APP_JPA_MODE
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: APP_JPA_MODE
        - name: APP_DB
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: APP_DB
        - name: APP_DB_DRIVER
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: APP_DB_DRIVER
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: sigecap-config
              key: APP_DEBUG
        - name: APP_SECRET #SOLO PARA FINES DIDACTICOS. REEMPLAZAR POR SECRET DE KUBERNETES
          valueFrom:
            configMapKeyRef:
              name: sigecap-config # jst-secret
              key: APP_SECRET
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: sigecap
spec:
  type: LoadBalancer
  selector:
    app: sigecap
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432